name: fastMRI
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=10.2.89
  - numpy=1.20.3
  - pip=21.0.1
  - python=3.8.11
  - pytorch=1.9.0
  - torchaudio=0.9.0
  - torchvision=0.10.0
  - pip:
    - fastmri==0.1.1
    - h5py==3.4.0
    - matplotlib==3.4.3
    - pytorch-lightning==1.0.8
    - pywavelets==1.1.1
    - pyyaml==5.4.1
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - runstats==2.0.0
    - scikit-image==0.18.3
    - scipy==1.7.1
    - tensorboard==2.6.0
    - tqdm==4.62.2
